### ISSUE TITLE
the module needs a less generic name, it is impossible to find

### ISSUE THREAD

**Issue by omnikron** [STRML/textFit#15]
I've spent about two days trying to figure out how to resize user-inputted and -formatted text of extremely varying length and markup to fit a container with a rigidly set height. Absolutely **none** of the other plugins I have tried (fitText, flowtype, fillText, any other combination of the words fit, text, and resize with a .js at the end) can do this, because they mostly focus on container width and/or only deal with one level of nesting, usually they just want a container div with a single `span` inside.  My own attempts were not very successful either.

textFit was the very last thing that I found before giving up, and I can't remember what bizarre combination of search terms led me here. I may have even overlooked it previously thinking that it was one I had already tried. It worked instantly without me needing to do anything at all and I am still reeling from the shock.  Have you considered maybe giving this INCREDIBLE plugin a less generic name so that it doesn't get swallowed up among all the others that pop up when you type the words fit and text into google? The world needs to know about this! You've solved the unsolveable!

Anyway. Really I just wanted to say thank you so much for making this fantastic and beautiful thing, but I couldn't open an issue just for that. But thank you. I am extremely grateful.

**Comment by STRML** [comment]
Thanks for the kind words. I originally built this plugin for headlines on brightestyoungthings.com (a very flamboyant website) and have just been keeping it up since.

It's hard from unsolvable, but I was as surprised as anyone that the current solutions had so much trouble with `line-height`, custom fonts, and that (at the time) all of them used simple iteration to find the correct size (slow, slow, slow). It needed to be fast enough to run on a production site, even on terrible JS engines like IE8.

If you have a suggestion for a better name, I'm all ears; it was previously `jquery-textfit` but I dropped the jQ dependency about a year ago. Yeah, it kind of gets lost, but fitting text is what it does.

Glad you're getting use out of the project. I like to hear that.

**Comment by STRML** [comment]
Before I close this - any ideas for a better name?
